kind: pipeline
name: tester

platform:
  os: linux
  arch: amd64

steps:
- name: security
  image: snyk/snyk-cli:npm
  pull: always
  environment:
    SNYK_TOKEN:
      from_secret: SNYK_TOKEN
  commands:
  - snyk monitor --all-projects

- name: install
  image: node:14
  commands:
  - npm install

- name: build
  image: node:14
  environment:
    NODE_ENV: production
  commands:
  - npm run build

---
kind: pipeline
name: publisher

platform:
  os: linux
  arch: amd64

steps:
- name: install
  image: node:14
  commands:
  - npm install

- name: build
  image: node:14
  environment:
    NODE_ENV: production
  commands:
  - npm run build

- name: publish
  image: plugins/npm
  settings:
    token:
      from_secret: NPM_DP_KEY
  commands:
  - npm publish

trigger:
  event:
    - tag

depends_on:
  - tester
